SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

CREATE TABLE A_LIST
(
	ORDER_ID int NOT NULL AUTO_INCREMENT,
	USER_ID varchar(15) NOT NULL,
	PRODUCT_ID int NOT NULL,
	ORDER_CNT int NOT NULL,
	ORDER_STATUS varchar(1) NOT NULL,
	PRIMARY KEY (ORDER_ID),
	UNIQUE (ORDER_ID)
);


CREATE TABLE A_PRODUCT
(
	PRODUCT_ID int NOT NULL AUTO_INCREMENT,
	PRODUCT_NAME char NOT NULL,
	PRODUCT_CNT int NOT NULL,
	PRODUCT_TYPE char(2),
	PRODUCT_SIZE char,
	PRIMARY KEY (PRODUCT_ID),
	UNIQUE (PRODUCT_ID)
);


CREATE TABLE A_SAL_LIST
(
	SAL_ID int NOT NULL AUTO_INCREMENT,
	PRODUCT_ID int NOT NULL,
	SAL_PRICE int NOT NULL,
	PRIMARY KEY (SAL_ID),
	UNIQUE (SAL_ID)
);


CREATE TABLE A_USER
(
	USER_ID varchar(15) NOT NULL,
	USER_NAME varchar(20) NOT NULL,
	USER_PW varchar(20) NOT NULL,
	USER_PHONE varchar(11) NOT NULL,
	USER_ADDR varchar(50) NOT NULL,
	REG_DT datetime DEFAULT now,
	UPDATE_DT datetime,
	USER_STATUS char(1),
	PRIMARY KEY (USER_ID),
	UNIQUE (USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE A_LIST
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES A_PRODUCT (PRODUCT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE A_SAL_LIST
	ADD FOREIGN KEY (PRODUCT_ID)
	REFERENCES A_PRODUCT (PRODUCT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE A_LIST
	ADD FOREIGN KEY (USER_ID)
	REFERENCES A_USER (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Create Views */

CREATE VIEW V_SAL_LIST AS select
 s.sal_id
 , p.product_name
 , p.product_cnt
 , p.product_type
 , p.product_size
 , s.sal_price
from
 a_sal_list  s
 , a_product p
where
 s.product_id = p.product_id;



